name: Tests

on:
    pull_request:
    push:
        branches: [1.x]
    schedule:
        - cron: '* 8 * * *'

jobs:
    tests:
        name: Tests
        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                dependencies:
                    - "locked"
                    - "lowest"
                    - "highest"
                php-version:
                    - "7.4"
                operating-system:
                    - "ubuntu-latest"
                    - "windows-latest"

        services:
            postgres:
                image: postgres:11.2
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: postgres
                ports:
                    - 5432/tcp
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: pcov
                  tools: composer:v2
                  php-version: "${{ matrix.php-version }}"
                  ini-values: memory_limit=-1

            - name: Get Composer Cache Directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache Composer dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      ${{ steps.composer-cache.outputs.dir }}
                  key: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.lock') }}"
                  restore-keys: |
                      php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-

            - name: Install lowest dependencies
              if: ${{ matrix.dependencies == 'lowest' }}
              run: "composer update --prefer-lowest --no-interaction --no-progress --no-suggest"

            - name: Install highest dependencies
              if: ${{ matrix.dependencies == 'highest' }}
              run: "composer update --no-interaction --no-progress --no-suggest"

            - name: Install locked dependencies
              if: ${{ matrix.dependencies == 'locked' }}
              run: "composer install --no-interaction --no-progress --no-suggest"

            - name: Run tests
              run: composer test
              env:
                  DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:${{ job.services.postgres.ports[5432] }}/postgres?serverVersion=11&charset=utf8
              timeout-minutes: 2
